AWSTemplateFormatVersion: "2010-09-09"
Description: IoT-ETL-Sample-Deploy-Bucket

Resources:
  # Lambdaコード等をデプロイするS3バケット
  DeployBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub iot-etl-sample-deploy-bucket-${AWS::AccountId}-${AWS::Region}
